# needed to validate the config yaml
defaults:
  - base_config
  - _self_

run_name: "base"
seed: 42
gpus: "1"
num_workers: 6
fast: false

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  # path to directory containing input data
  input_dir: "${hydra:runtime.cwd}/data"
  # path to directory to save output data
  output_dir: "${hydra:runtime.cwd}/output"

model:
  learning_rate: 0.0001

train:
  batch_size: 16
  max_epochs: 5
